In [2]:
import numpy as np

In [3]:
input = np.load('/data1/intern/hanl/find_polygon/input/basic/00.npy')

In [15]:
sum = np.zeros(input.shape[0]).T
print(sum.shape)
for i in range(input.shape[1]):
    xi = input[:,i]
    sum+=xi
sum /= input.shape[1]


(3303,)


In [21]:
std_input = np.copy(input).astype(np.float32)
std_input

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [22]:
for i in range(input.shape[1]):
    std_input[:,i] -=sum

In [23]:
S = std_input@std_input.T/input.shape[1]

In [24]:
S

array([[1.9840314e+08, 1.8188565e+08, 1.4472237e+08, ..., 3.9097076e+07,
        2.6673774e+07, 3.1685738e+06],
       [1.8188565e+08, 3.7444512e+08, 3.0420208e+08, ..., 1.0195285e+08,
        5.3245360e+07, 7.3025430e+06],
       [1.4472237e+08, 3.0420208e+08, 6.9269670e+08, ..., 2.0517966e+08,
        1.0726580e+08, 2.6490092e+07],
       ...,
       [3.9097076e+07, 1.0195285e+08, 2.0517966e+08, ..., 7.8035629e+08,
        4.5373242e+08, 2.5216269e+08],
       [2.6673774e+07, 5.3245360e+07, 1.0726580e+08, ..., 4.5373242e+08,
        5.4020986e+08, 3.0282589e+08],
       [3.1685738e+06, 7.3025430e+06, 2.6490092e+07, ..., 2.5216269e+08,
        3.0282589e+08, 3.3235235e+08]], dtype=float32)

In [36]:
eigen_value, eigen_vector = np.linalg.eig(S)

In [37]:
per_eig = eigen_value/np.sum(eigen_value)

In [38]:
count =0
sum_per =0
for i in per_eig:
    sum_per+=i
    count+=1
    if (sum_per>0.99): break

In [48]:
Uk = eigen_vector[:,:count]

In [50]:
pca = np.dot(Uk.T,std_input)

In [52]:
std_input

array([[ -4306.6455,  -4306.6455,  -4306.6455, ...,  -4307.6455,
         -4307.6455,  -4307.6455],
       [ -8141.3306,  -8141.3306,  -8141.3306, ...,  -8142.3306,
         -8142.3306,  -8142.3306],
       [-16768.5   , -16768.5   , -16768.5   , ..., -16769.5   ,
        -16769.5   , -16769.5   ],
       ...,
       [-18870.662 , -18870.662 , -18870.662 , ..., -18870.662 ,
        -18870.662 , -18870.662 ],
       [-11031.384 , -11031.384 , -11031.384 , ..., -11031.384 ,
        -11031.384 , -11031.384 ],
       [ -6462.7803,  -6462.7803,  -6462.7803, ...,  -6462.7803,
         -6462.7803,  -6462.7803]], dtype=float32)

In [51]:
pca

array([[-9.6964800e+05, -9.6857394e+05, -9.6673256e+05, ...,
         1.5181695e+06,  4.3513322e+05, -2.1499769e+05],
       [ 4.1745068e+03,  4.2219233e+03,  4.0614385e+03, ...,
         4.7253769e+05,  3.6417406e+05,  2.5591308e+05],
       [-2.3082285e+03, -2.0631055e+03, -1.9183926e+03, ...,
        -6.9385075e+05, -5.8710638e+05, -4.2948512e+05],
       ...,
       [-2.7027222e+02, -2.3349890e+02, -3.8674561e+02, ...,
         1.6015146e+04, -9.6666943e+03,  4.7925752e+03],
       [ 7.9334021e+02,  7.3951013e+02,  6.4182629e+02, ...,
         1.0170580e+04, -3.1815273e+03,  6.5159014e+03],
       [ 7.6675854e+02,  7.6086780e+02,  8.0284583e+02, ...,
        -3.1305320e+03, -2.5719485e+03,  1.5267506e+04]], dtype=float32)

In [5]:
a = [[1,2],[3,4]]
b = np.mean(a, axis=0)

In [6]:
b.T


array([2., 3.])